//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class content_order_ingredients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public content_order_ingredients()
        {
            this.shipment = new HashSet<shipment>();
        }
    
        public int id { get; set; }
        public int count { get; set; }
        public int price { get; set; }
        public int order_ingredients_id { get; set; }
        public int ingredient_id { get; set; }
        public Nullable<int> unit_of_measurement_id { get; set; }
    
        public virtual units_of_measurement units_of_measurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shipment> shipment { get; set; }
        public virtual ingredients ingredients { get; set; }
        public virtual order_ingredients order_ingredients { get; set; }
    }
}
