//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_ingredients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_ingredients()
        {
            this.content_order_ingredients = new HashSet<content_order_ingredients>();
        }
    
        public int id { get; set; }
        public System.DateTime order_time { get; set; }
        public System.DateTime execute_time { get; set; }
        public Nullable<int> provider_id { get; set; }
        public Nullable<int> status_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<content_order_ingredients> content_order_ingredients { get; set; }
        public virtual providers providers { get; set; }
        public virtual statuses statuses { get; set; }
    }
}
