//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders()
        {
            this.checks = new HashSet<checks>();
        }
    
        public int id { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> table_id { get; set; }
        public Nullable<int> waiter_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<checks> checks { get; set; }
        public virtual statuses statuses { get; set; }
        public virtual platens platens { get; set; }
        public virtual waiters waiters { get; set; }
    }
}
