//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipes
    {
        public int id { get; set; }
        public int menu_id { get; set; }
        public int ingredient_id { get; set; }
        public int count { get; set; }
        public Nullable<int> unit_of_measurement_id { get; set; }
    
        public virtual ingredients ingredients { get; set; }
        public virtual menu menu { get; set; }
        public virtual units_of_measurement units_of_measurement { get; set; }
    }
}
