//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_Restaurant1Entities : DbContext
    {
        public Project_Restaurant1Entities()
            : base("name=Project_Restaurant1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<checks> checks { get; set; }
        public virtual DbSet<content_order_ingredients> content_order_ingredients { get; set; }
        public virtual DbSet<cooking> cooking { get; set; }
        public virtual DbSet<ingredients> ingredients { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<order_ingredients> order_ingredients { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<platens> platens { get; set; }
        public virtual DbSet<providers> providers { get; set; }
        public virtual DbSet<recipes> recipes { get; set; }
        public virtual DbSet<shipment> shipment { get; set; }
        public virtual DbSet<statuses> statuses { get; set; }
        public virtual DbSet<storage_ingredient> storage_ingredient { get; set; }
        public virtual DbSet<type_dish> type_dish { get; set; }
        public virtual DbSet<units_of_measurement> units_of_measurement { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<waiters> waiters { get; set; }
    }
}
